### ISSUE TITLE
More IP addresses for the snowflake-01 bridge

### ISSUE THREAD

**Issue by uumaro** [Enkidu-6/tor-ddos#25]
This is David Fifield, one of the admins of the snowflake-01 bridge. Cc @ln5, the other admin.

Thank you for including an exception for the IP addresses of snowflake-01.torproject.net. Since https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/issues/40223, the bridge uses additional outbound IP addresses. It would be nice if the script had exceptions for them too.

Forward DNS resolution of snowflake-01.torproject.net will return only the .42 and :42 addresses.

```
193.187.88.42 (existing)
193.187.88.43
193.187.88.44
193.187.88.45
193.187.88.46
2a0c:dd40:1:b::42 (existing)
2a0c:dd40:1:b::43
2a0c:dd40:1:b::44
2a0c:dd40:1:b::45
2a0c:dd40:1:b::46
```

**Comment by Enkidu-6** [comment]
Hi David. Gladly. I'm following [the main issue](https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/issues/40223#note_2859461) to find the best solution to implement this.

**Comment by Enkidu-6** [comment]
The script pulls the authorities from a list on my other repository https://github.com/Enkidu-6/tor-relay-lists/blob/main/authorities-v4.txt and authorities-v6.txt. For now, I've added the additional IP addresses to that list manually so no need to update the actual scripts. 

But I'm hoping for a better way to automate the process so in case of any future change to the IP addresses, it can be automatically updated at which point I'll make a modification to individual scripts. Currently I can't pull the addresses automatically because a Forward DNS resolution for those subdomains returns no address.

All users can update their allow list by running [refresh-authorities.sh](https://raw.githubusercontent.com/Enkidu-6/tor-ddos/main/cron/refresh-authorities.sh)
