### ISSUE TITLE
Adapt rules to ancient kernels and userlands?

### ISSUE THREAD

**Issue by tsjk** [Enkidu-6/tor-ddos#4]
Great initiative to provide helpful ways of coping with the DDOS attack.

I think it'd be great if the rules could be adapted to ancient kernels and userlands, so that they could be applied on routers - which usually are equipped with just that. It may also be good to not assume that we are alone in the universe, and I see you have taken steps in that direction by not flushing built-in chains. Adding the rules to a custom chain could be the next step, and deleting/adding just one rule to a built-in chain on (re-)run.

I'm happy to help, and have converted the ipset rules to ipset v4 syntax, I think. Had to use iptree instead of iphash for the drop lists, as iphash has no timeouts. Hope it has the same functionality...

I'm having some troubles with hashlimit, as that does not exist. I'll look at converting that to a connlimit or a recent.
I'm also struggling with
`iptables -t mangle -A TOR_RELAY_0 -p tcp --destination ${tor_relay__ipaddress} --destination-port ${tor_relay__orport} -m connlimit --connlimit-above 2 -j SET --add-set tor-drop-list-2 src`
I get (even though I removed `--connlimit-mask 32` - which is default, I think):
`iptables v1.3.8: --connlimit-above and/or --connlimit-mask may only be given once`
I fear old iptables has some bug here, and wonder if this can be rewritten in another way. I'll look at that.
The rule
`iptables -t mangle -A TOR_RELAY_0 -p tcp --destination ${tor_relay__ipaddress} --destination-port ${tor_relay__orport} -m recent --name tor-drop-list-2 --set`
seems to work...

**Comment by Enkidu-6** [comment]
Thanks for your contribution.

You should do a fork and make your modifications so I can see the whole picture. What I can deduce from the last rule in your comment - without having the full context - is that you are adding everyone to your tor-drop-list2, effectively blocking access to Tor.

As for modifying the rules to work on ancient kernels, it requires me to have one to test it on. I'm afraid I don't. But most importantly with every rule, we need to apply and test them for a period of time to see the effects it might have on the operations of the relay and the whole Tor network as a whole.

So since you do have the equipment, I suggest that you start a fork and do the testing, so we can have a more clear picture of the outcome.

As for flushing the tables, I do agree. I've reached the conclusion that since we're using mangle and practically all distribution that I know of have the allow policy out of the box, we may not have to flush anything before applying the rules. Flushing the ipsets though may pose a problem if other tables have a hold on an ipset. I'm looking at some modifications to the script but they have to be tested first, so follow the repository to get notified when the modifications are applied

Again, thanks for your comment. They're always welcome.
