### ISSUE TITLE
Debian 11 add install line in instructions

### ISSUE THREAD

**Issue by cozybear-dev** [Enkidu-6/tor-ddos#45]
Hi,

On a clean Debian 11 install, you'd need to install the following before running any scripts;

`sudo apt-get install iptables ipset curl`

If you want to make the changes persist through boots (my node autoreboots for automatic upgrading - this is not Debian 11 specific);

`sudo apt-get install iptables-persistent`

After updating iptables, use this command;

`sudo iptables-save`

Perhaps this could be added in the README, or elsewhere in the instructions.

**Comment by Enkidu-6** [comment]
Hi,

Strange, because my Debian 11 does come with iptables. Well, nf_tables but just the same. iptables -V shows 
iptables v1.8.7 (nf_tables) and I'm sure I didn't install it. It has curl as well, although I'm not sure if I installed it myself or not. You are correct about the ipset on my Debian though. It doesn't come with it.

I do have a mention about checking to see if you have them already [here on the second paragraph](https://github.com/Enkidu-6/tor-ddos/blob/main/README.md#iptables-what-we-should-know)

No need to install ip-tables as nf_tables gladly accepts iptables rules.

As for making it persistent, I have avoided it on purpose. I don't like to make modifications to people's systems that take effort to reverse. I like the fact that on CentOS for example, reversing the whole thing is as simple as typing firewall-cmd --reload.

Also, in order to use iptables-save, you don't need the persistent package. It's a part of iptables  / nf_tables package.

I will add a comment about curl for sure. I never thought about it as I use it quite often on different systems and I can't remember having to install it, or if I have, I've been on auto pilot and can't remember. :-) I'll add the an explanation to the TLDR section as well since people may never get as far as the link above in the README

**Comment by Enkidu-6** [comment]
Done. [4ef2cfb](https://github.com/Enkidu-6/tor-ddos/commit/4ef2cfbf55e63eef0aa77f4bd379daf7e208c557)

**Comment by cozybear-dev** [comment]
Thanks for the quick extensive replies! Appreciate it. Testing the scripts on my Tor node today, hence the issue creation...

**Comment by Enkidu-6** [comment]
Sounds good. Please make sure you pick up the newest version. I made some modifications.
