### ISSUE TITLE
Configure iptables with UFW

### ISSUE THREAD

**Issue by Superpaul209** [Enkidu-6/tor-ddos#5]
Hello,

First of all, thank you for your help for the tor network, we all appreciate your work !

I would like to know how can I configure your iptables to work with UFW ? I can't set iptables manually since ufw overwrites them all the time. Can you provide some steps to do that please ?
I have seen this post : https://serverfault.com/questions/198398/ubuntu-how-to-add-an-iptables-rule-that-ufw-cant-create
The main problem is that I don't know if your iptables are before or after in UFW.

Thanks !

**Comment by Enkidu-6** [comment]
Hi,
I don't claim to be a UFW expert. I'm not an UBUNTU guy myself but I believe the only time UFW rewrites the rules is when you reboot or add a rule to UFW and restart or reload it. If you regularly change the rules, then yes, that could be annoying.

Regardless, set up your firewall the way you like, then run the scripts to apply the iptables rules. Once it's done and everything is in working order, if you don't already have any after rules, you can use the following command:

iptables-save -t mangle > /etc/ufw/after.rules

This will overwrite your current after rules.

This command writes the mangle rules to the after file. The mangle rules is all you need. However please note, I'm not sure what UFW does to ipset rules once it reloads. If it deletes your ipsets, you will still need to create them all over again because the rules point to the ipset and if they're not there, then they won't work

**Comment by Enkidu-6** [comment]
I just added two files: ipset-backup.sh and ipset-restore.sh so you can backup all ipsets before a reboot or modifying the UFW rules for example, and restore them after.

**Comment by cybermonkee** [comment]
> Hello,
> 
> First of all, thank you for your help for the tor network, we all appreciate your work !
> 
> I would like to know how can I configure your iptables to work with UFW ? I can't set iptables manually since ufw overwrites them all the time. Can you provide some steps to do that please ? I have seen this post : https://serverfault.com/questions/198398/ubuntu-how-to-add-an-iptables-rule-that-ufw-cant-create The main problem is that I don't know if your iptables are before or after in UFW.
> 
> Thanks !

Hi There, 

I use UFW on debian, what I did was disable UFW, and then run the commands that are recommended, I then started UFW. Finally, I then checked that the IPSets could be found in the mangle by running the following command:

 iptables -t mangle --list

This confirmed to me that UFW had not caused an issue.

I then ran the following commands to check that the rules were catching the attack
ipset -L persec 
ipset -L tor-ddos | more

I have not tried a reboot yet, but what I will probably do, on rebooting is check this git repository for updates, and configure all the firewalling from fresh each time. Although it would be good if these commands could be scripted and included in the tor package update.

I can confirm this has worked for me so far, and it has greatly helped with the amount of overload messages. It has also helped with my understanding of iptables - which is pretty poor TBH...

**Comment by Superpaul209** [comment]
Thank you both for your answers

I have applied iptables rules with the script and also backed up rules to put them into after.rules
After a service restart, rules are still there, its perfect ! I will try later to reboot my server to see if it still applies them.

Im seeing good results for now on my relay, it isn't stuck at the maximum bandwidth anymore and I get less warnings. I already have 122 entries in the tor-ddos ipset list... I will watch my relay for some time 👍 😄

**Comment by cybermonkee** [comment]
Check this out: 
Name: tor-ddos
Type: hash:ip
Revision: 4
Header: family inet hashsize 4096 maxelem 65536 timeout 43200
Size in memory: 218192
References: 2
Number of entries: 2686
Members:

I also ran the compare.sh through wc to count the lines... 
./compare.sh | wc -l
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 86781  100 86781    0     0   120k      0 --:--:-- --:--:-- --:--:--  120k
95
root@aaa.bbb.ccc.ddd:/home/tor#

95 relays are on my blocked list... that's quite a few - but I do agree that, we have to filter the ingress into the ToR cloud.
