### ISSUE TITLE
refresh-authorities.sh

### ISSUE THREAD

**Issue by ToterEngel** [Enkidu-6/tor-ddos#60]
The new version in the dev-branch generated many error messages.  :-)

`ipset v7.10: The set with the given name does not exist`

**Comment by Enkidu-6** [comment]
That's why it's in the dev branch lol. It's designed to work with the new multi.sh in the dev branch. It's something I've been experimenting with for the past few days and I don't want to release it without further testing. It's quite effective but at a cost of using more resources. You're welcome to play with it if you like. Just use the update.sh in the dev branch.

If you decide to use it please let me know if it's using too much RAM or it's just me. I moved my relays to a new version of the OS and I'm not sure if it's the OS using more RAM or the rules.

**Comment by Enkidu-6** [comment]
Please use the newest update.sh in the dev branch. I just noticed that I needed to make a change. I'd done it on my system but forgot to update the repo.
