### ISSUE TITLE
script keeps downloading the list

### ISSUE THREAD

**Issue by cybermonkee** [Enkidu-6/tor-ddos#8]
#!/bin/bash
# set -x
/usr/sbin/ipset -L tor-ddos | awk '{print $1}' > /var/tmp/file1
**if [[ ! -e /var/tmp/file2 ]]; then**
curl -s 'https://raw.githubusercontent.com/Enkidu-6/tor-relay-lists/main/dual-or.txt' > /var/tmp/dual-or
elif
[[ $(find "**/var/tmp/file2**" -mmin +60 -print) ]]; then
curl -s 'https://raw.githubusercontent.com/Enkidu-6/tor-relay-lists/main/dual-or.txt' > /var/tmp/dual-or
fi
cd /var/tmp
perl -ne 'print if ($seen{$_} .= @ARGV) =~ /10$/'  file1 dual-or > dual
for i in `cat dual` ;
do
/usr/sbin/ipset del tor-ddos $i
done;

Should read:
/var/tmp/dual-or

**Comment by Enkidu-6** [comment]
That's not the problem. It should be cat dual. dual-or is the full list. You wouldn't want to try to remove the full list from your  block list, only the ones that are actually in your block list. The problem was having a wrong file name . Instead of file2 it should have been dual-or. Fixed now. Give it a try.
