### ISSUE TITLE
Wrong last line in 2-or-v6.txt and 2-or.txt?

### ISSUE THREAD

**Issue by bolle732** [Enkidu-6/tor-ddos#86]
There is a last line with `Thu` In the files

https://raw.githubusercontent.com/Enkidu-6/tor-relay-lists/main/2-or-v6.txt
```
...
2a10:3781:1854:1::2d53:ea72
Thu
```

and

https://raw.githubusercontent.com/Enkidu-6/tor-relay-lists/main/2-or.txt
```
98.128.173.1
Thu
```

I think this isn't by intention.

**Comment by Enkidu-6** [comment]
Hmm... It's not there, and I can't take credit for fixing it. I did see it though when I clicked on your link earlier today. It must have been some kind of a hiccup in the cron job or some quirk in the original source. Can't tell what it was but the problem seems to have disappeared. I'll keep an eye on it.

How did you find it? Did you get an error message when running refresh-authorities.sh? The good thing is, some nonsense like that showing up in the IP list won't affect the rest of the operation. It'll simply tell you it can't be added to the ipset and keeps adding the rest.

**Comment by ToterEngel** [comment]
I also noticed this yesterday, but only through a warning mail from cron:

```
Warning: Thu resolves to multiple addresses: using only the first one returned by the resolver.
ipset v7.10: Syntax error: cannot parse Thu: resolving to IPv6 address failed
```

**Comment by bolle732** [comment]
I found this by chance when reviewing my Tor node due to some behavior in the load of the last days. The load dropped a lot for about a week and increased again even the throughput stayed at the same level.

I use my own script based on yours and the OR files you provide. I believe this `Thu` came from the 3 line header. It went in some way to the last line in the file. This did nothing bad to the iptables. Only the first real IP would be missed in the ipset as we cut the first 3 lines (the header).

**Comment by Enkidu-6** [comment]
I haven't seen the problem again in the subsequent files. Since I haven't changed or modified the script that extracts the data, I'm assuming this must have been due to a temporary glitch in the source data from onionoo. I'll still keep an eye on it though.

I'm closing this issue for the time being. Feel free to reopen it if you see the problem again.
