### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by ToterEngel** [Enkidu-6/tor-ddos#9]
I'm currently using Munin for monitoring.

To monitor the banned IPs and affected relays, can you craft a plugin for that?

**Comment by Enkidu-6** [comment]
I'm afraid I don't use Munin and writing a plugin for it is outside the scope of this Repository and probably my skills. But you can always monitor the numbers by running a cron job with a script. 

I just made one in the dev branch of the Repository here:

wget https://raw.githubusercontent.com/Enkidu-6/tor-ddos/dev/cron/monitor.sh 

The results are going to /var/tmp/relays.log and ipset.log

you can run it with a cron job as often as you wish. Or you can modify or make your own scripts to do similar jobs. Just remember that if you're running remove.sh script - in the cron directory - that removes the relays from the block list regularly, like I do, then this script may not show you any relays in the block list, well, because there aren't going to be any.
