### ISSUE TITLE
Fetching authorities-v4.txt failed

### ISSUE THREAD

**Issue by maherbo** [Enkidu-6/tor-ddos#91]
Fetching the file "https://raw.githubusercontent.com/Enkidu-6/tor-relay-lists/main/authorities-v4.txt" in _refresh-authorities.sh_ has been returning the following for the last few days:

```
Updated:
Mon Oct 2 2023 03:00:02 UTC
----------------------------
  </head>
  <body>
Backend fetch failed</h1>
ch failed</p>
ation
65</p>
    <hr>
he server</p>
  </body>
</html>
```

**Comment by Enkidu-6** [comment]
Hi, I haven't changed the scripts. There might be hiccup from time to time when pulling the lists from onionoo server which results in errors in the files. The problem gets corrected much faster with the other lists that are updated every 30 minutes, but the authorities are not updated as often because they hardly ever change. Which means when there's a hiccup, it stays there much longer.

The list is okay right now but I'll keep an eye on it just in case.

Thanks you.
