### ISSUE TITLE
Wrong encoding of multi.sh -> "-bash: ./multi.sh: cannot execute: required file not found"

### ISSUE THREAD

**Issue by PacaAlpaca** [Enkidu-6/tor-ddos#94]
Hi, i tried to run v7.0.1 (using command from readme -> download.sh) but got weird error, from what I check it looks like there is a Windows file encoding in multi.sh which throws error in Linux shell.

![obraz](https://github.com/Enkidu-6/tor-ddos/assets/112646966/f3a1bc52-9d0d-4457-aff9-aef7d5bcfbb0)

Using `cat -A multi.sh`:

v7.0.0 -> works OK

![obraz](https://github.com/Enkidu-6/tor-ddos/assets/112646966/36f0cc9e-7afa-4334-8523-1e9dafd7be6e)

v7.0.1 -> "-bash: ./multi.sh: cannot execute: required file not found"

![obraz](https://github.com/Enkidu-6/tor-ddos/assets/112646966/af780a43-ff07-4e2e-b51d-1b16de4858c3)

![obraz](https://github.com/Enkidu-6/tor-ddos/assets/112646966/2eee9223-e491-471a-b7ff-7e589165aee2)

In linux I can convert file by using command `dos2unix multi.sh` but it rather should be changed in git repo :)

**Comment by Enkidu-6** [comment]
Sorry about that. I'd switched the settings in VSCode and forgot to switch back. The $ at the end of each line is not what causes the problem. They've been there since the beginning. It's the ^M.

You can get rid of them by typing:
```
sed -i -e 's/\r$//' scriptname.sh
```
I will fix that shortly and again thank you for your great input.

Cheers
